@Library("shared-library@main")_

pipeline{
    agent any
    // tools {nodejs "Node"}

    stages {
        /* groovylint-disable-next-line UnnecessaryGString */
        stage("Checkout target branch") {
            steps {
                checkout scm
            }
        }
        /* groovylint-disable-next-line UnnecessaryGString */
        stage ("build image") {
            steps {
                buildImage 'testauto40'
            }
        }
        stage ("publish image") {
            steps {
                loginDocker()
            }
        }
    }
}
